services:
  - type: web
    name: morgan-mngadi-portfolio
    runtime: static
    buildCommand: pnpm run build:portfolio:ssr
    staticPublishPath: artifacts/portfolio/dist/public
    renderSubdomainPolicy: enabled
    domains:
      - morganmngadi.com
    previews:
      generation: automatic
