services:
  - type: web
    name: cv-portfolio-5tuf
    runtime: static
    buildCommand: pnpm run build:portfolio:ssr
    staticPublishPath: artifacts/portfolio/dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /404/index.html
    renderSubdomainPolicy: enabled
    domains:
      - morgan-mngadi-portfolio.online
      - www.morgan-mngadi-portfolio.online
    previews:
      generation: automatic
